version: "2"

services:
  collector:
    image: ghcr.io/solectrus/senec-collector:latest
    environment:
      - SENEC_HOST
      - SENEC_INTERVAL
      - INFLUX_HOST
      - INFLUX_TOKEN
      - INFLUX_ORG
      - INFLUX_BUCKET
      - FORECAST_LATITUDE
      - FORECAST_LONGITUDE
      - FORECAST_DECLINATION
      - FORECAST_AZIMUTH
      - FORECAST_KWP
      - FORECAST_INTERVAL
    command: bundle exec app/main.rb
    network_mode: host
    privileged: true
    restart: unless-stopped
